server:
  port: 9091

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: login-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/login-service/**
          filters:
            - StripPrefix=2
        - id: system
          uri: http://localhost:8092
          predicates:
            - Path=/api/system-service/**
          filters:
            - StripPrefix=2
        - id: user
          uri: http://localhost:8093
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
#logging:
#    file:
#        name: D:/log/gateway.log
#    level:
#        springfox: error
#        cn.edu.sgu.www.gateway: debug